-- REVIEW-ONLY DEV/QA MIRROR. NEVER APPLY TO DRONA/AWS.
-- Candidate based on the uploaded four-table CSV and documented role join.
-- Unconfirmed choices: modules=text[], generated identity sequence definitions,
-- and the minimal two-column role catalog. These are NOT certified AWS parity.
-- Preserve all current shared/app schemas; existing records are not replaced.
-- An authorized operator must review the target and set the session setting
-- qms360.migration_environment to 'dev' or 'qa' before executing this package.
-- The setting is a safety acknowledgement, not proof of database identity.
BEGIN;
DO $$
BEGIN
  IF current_setting('qms360.migration_environment', true) IS NULL
     OR current_setting('qms360.migration_environment', true) NOT IN ('dev', 'qa') THEN
    RAISE EXCEPTION 'DEV/QA mirror requires explicit target review';
  END IF;
  IF to_regclass('public.user_master') IS NOT NULL
     OR to_regclass('public.project_master') IS NOT NULL
     OR to_regclass('public.user_role_master') IS NOT NULL
     OR to_regclass('public.project_mapping') IS NOT NULL
     OR to_regclass('public.user_role_mapping') IS NOT NULL THEN
    RAISE EXCEPTION 'Source tables already exist; compare schemas instead of recreating them';
  END IF;
END $$;

CREATE TABLE public.user_master (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name varchar(255) NOT NULL,
  user_email varchar(255) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  phone_number varchar,
  badge_no varchar(255) DEFAULT NULL,
  user_sign text,
  created_by bigint,
  updated_by bigint
);

CREATE TABLE public.project_master (
  project_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_name varchar(255) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  observation_project_id bigint,
  hse_observation_count jsonb,
  enable_ptw boolean DEFAULT false,
  observation_count jsonb,
  enable_quality boolean NOT NULL DEFAULT false,
  enable_fleet boolean DEFAULT false,
  module varchar(255),
  modules text[] DEFAULT '{}',
  contract_number varchar(100),
  project_code bigint,
  region_id integer
);

CREATE TABLE public.user_role_master (
  user_role_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_role varchar(255) NOT NULL
);

CREATE TABLE public.project_mapping (
  project_map_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sbg_id integer NOT NULL,
  bu_id integer NOT NULL,
  division_id integer NOT NULL,
  project_id bigint NOT NULL REFERENCES public.project_master(project_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  department_id integer,
  modules text[] DEFAULT '{}'
);

CREATE TABLE public.user_role_mapping (
  user_role_map_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_map_id bigint NOT NULL REFERENCES public.project_mapping(project_map_id),
  user_id bigint NOT NULL REFERENCES public.user_master(user_id),
  user_role_id integer NOT NULL REFERENCES public.user_role_master(user_role_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_coordinator boolean DEFAULT false,
  module varchar(255),
  modules text[] DEFAULT '{}',
  is_active boolean DEFAULT true
);

-- Candidate DEV/QA query indexes; inspect the actual AWS definitions separately.
CREATE INDEX drona_dev_assignment_user_idx ON public.user_role_mapping(user_id);
CREATE INDEX drona_dev_assignment_slot_idx ON public.user_role_mapping(project_map_id);
CREATE INDEX drona_dev_slot_project_idx ON public.project_mapping(project_id);
COMMIT;