export default function BackendArchitecture() {
  return <div className="w-screen h-screen overflow-hidden relative bg-bg px-[4vw] py-[4vh] font-body text-primary grid grid-rows-[auto_auto_1fr_auto] gap-y-[2.2vh]">
    <header className="flex items-center justify-between border-b border-slate-200 pb-[2vh]"><div className="flex items-center gap-[1vw]"><div className="h-[2vw] w-[2vw] rounded-[0.4vw] bg-accent"></div><span className="text-[1.5vw] font-bold">QMS360</span></div><span className="text-[1.5vw] font-semibold text-muted">BACKEND + DATA</span></header>
    <div><p className="text-[1.5vw] font-bold uppercase tracking-[0.12em] text-accent">Service and persistence layers</p><h1 className="text-[3.8vw] font-extrabold tracking-[-0.035em]">Backend, API, and data architecture</h1></div>
    <main className="grid grid-cols-[0.9fr_1.15fr_0.95fr] gap-[1.5vw]">
      <section className="rounded-[1vw] border border-slate-200 bg-white p-[1.6vw] shadow-[0_0.5vw_1.5vw_rgba(30,58,95,0.06)]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-accent">Runtime</p><p className="mt-[1vh] text-[2.2vw] font-extrabold">Node.js + Express 5</p><p className="mt-[1.2vh] text-[1.55vw] leading-[1.4] text-muted">Modular API server</p><div className="my-[2vh] h-px bg-slate-200"></div><p className="text-[1.5vw] font-bold uppercase tracking-wide text-muted">REST groups</p><p className="mt-[1vh] text-[1.5vw] leading-[1.45] text-muted">auth · platform · QA/QC · Lessons · Audit · integrations · notifications · feedback</p></section>
      <section className="rounded-[1vw] border border-teal-200 bg-teal-50 p-[1.6vw]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-accent">Contract + validation</p><p className="mt-[1vh] text-[2.2vw] font-extrabold">OpenAPI 3.1</p><p className="mt-[1.2vh] text-[1.55vw] leading-[1.4] text-muted">Generates React Query clients and Zod schemas</p><div className="mt-[2vh] rounded-[0.7vw] bg-white p-[1.2vw] text-center text-[1.55vw] font-semibold">Specification</div><div className="text-center text-[2vw] text-accent">↓</div><div className="rounded-[0.7vw] bg-white p-[1.2vw] text-center text-[1.55vw] font-semibold">Generated clients + schemas</div><div className="text-center text-[2vw] text-accent">↓</div><div className="rounded-[0.7vw] bg-white p-[1.2vw] text-center text-[1.55vw] font-semibold">Validated business logic</div><p className="mt-[1.3vh] text-[1.5vw] leading-[1.35] text-muted">Request payloads parsed at API boundaries before business logic</p></section>
      <section className="rounded-[1vw] bg-primary p-[1.6vw] text-white"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-teal-300">Persistence</p><p className="mt-[1vh] text-[2.2vw] font-extrabold">PostgreSQL</p><p className="mt-[1vh] text-[1.5vw] leading-[1.4] text-slate-200">Drizzle ORM and node-postgres pooling</p><div className="mt-[2vh] space-y-[1vh] text-[1.5vw] font-semibold"><p className="rounded-[0.6vw] bg-white/10 p-[1vw]">shared / platform</p><p className="rounded-[0.6vw] bg-white/10 p-[1vw]">QA/QC schema</p><p className="rounded-[0.6vw] bg-white/10 p-[1vw]">Lessons schema</p><p className="rounded-[0.6vw] bg-white/10 p-[1vw]">Audit schema</p></div><p className="mt-[1.6vh] text-[1.5vw] leading-[1.35] text-slate-200">Transactions, tenant filters, audit records, soft deletion, and domain-specific concurrency controls</p></section>
    </main>
    <footer className="flex items-center justify-between border-t border-slate-200 pt-[2vh] text-[1.5vw] font-medium text-slate-400"><span>QMS360 Platform</span><span>Architecture Overview • 04</span></footer>
  </div>;
}
