export default function FrontendArchitecture() {
  return <div className="w-screen h-screen overflow-hidden relative bg-bg px-[4vw] py-[4vh] font-body text-primary grid grid-rows-[auto_auto_1fr_auto] gap-y-[2.3vh]">
    <header className="flex items-center justify-between border-b border-slate-200 pb-[2vh]"><div className="flex items-center gap-[1vw]"><div className="h-[2vw] w-[2vw] rounded-[0.4vw] bg-accent"></div><span className="text-[1.5vw] font-bold">QMS360</span></div><span className="text-[1.5vw] font-semibold text-muted">FRONTEND</span></header>
    <div><p className="text-[1.5vw] font-bold uppercase tracking-[0.12em] text-accent">Browser application</p><h1 className="text-[4vw] font-extrabold tracking-[-0.035em]">Frontend architecture</h1></div>
    <main className="grid grid-cols-[1.15fr_0.85fr] gap-[2vw]">
      <section className="grid grid-cols-2 gap-[1.2vw]">
        <div className="rounded-[0.9vw] border border-teal-200 bg-teal-50 p-[1.5vw]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-accent">Language</p><p className="mt-[1vh] text-[2vw] font-extrabold">TypeScript</p><p className="mt-[0.7vh] text-[1.55vw] leading-[1.4] text-muted">React components and TSX</p></div>
        <div className="rounded-[0.9vw] border border-slate-200 bg-white p-[1.5vw]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-muted">Build/runtime</p><p className="mt-[1vh] text-[2vw] font-extrabold">Vite</p><p className="mt-[0.7vh] text-[1.55vw] leading-[1.4] text-muted">Development, build, and preview pipeline</p></div>
        <div className="rounded-[0.9vw] border border-slate-200 bg-white p-[1.5vw]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-muted">UI</p><p className="mt-[1vh] text-[1.9vw] font-extrabold">Tailwind + Radix</p><p className="mt-[0.7vh] text-[1.5vw] leading-[1.35] text-muted">Reusable component layer and Lucide icons</p></div>
        <div className="rounded-[0.9vw] border border-slate-200 bg-white p-[1.5vw]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-muted">State</p><p className="mt-[1vh] text-[1.9vw] font-extrabold">React Query</p><p className="mt-[0.7vh] text-[1.5vw] leading-[1.35] text-muted">API cache; controlled forms with React Hook Form</p></div>
        <div className="rounded-[0.9vw] border border-slate-200 bg-white p-[1.5vw]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-muted">Navigation</p><p className="mt-[1vh] text-[1.9vw] font-extrabold">Wouter</p><p className="mt-[0.7vh] text-[1.5vw] leading-[1.35] text-muted">Client-side routing with authenticated route protection</p></div>
        <div className="rounded-[0.9vw] border border-slate-200 bg-white p-[1.5vw]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-muted">Data contracts</p><p className="mt-[1vh] text-[1.9vw] font-extrabold">Generated hooks</p><p className="mt-[0.7vh] text-[1.5vw] leading-[1.35] text-muted">Typed hooks from the shared OpenAPI specification</p></div>
      </section>
      <aside className="rounded-[1vw] bg-primary p-[2vw] text-white shadow-[0_0.8vw_2vw_rgba(30,58,95,0.16)]"><p className="text-[1.5vw] font-bold uppercase tracking-[0.12em] text-teal-300">Product surfaces</p><div className="mt-[2vh] grid grid-cols-2 gap-[1.1vw] text-[1.65vw] font-semibold"><div className="rounded-[0.7vw] bg-white/10 p-[1.2vw]">QA/QC</div><div className="rounded-[0.7vw] bg-white/10 p-[1.2vw]">Lessons</div><div className="rounded-[0.7vw] bg-white/10 p-[1.2vw]">Audit</div><div className="rounded-[0.7vw] bg-white/10 p-[1.2vw]">Executive</div><div className="rounded-[0.7vw] bg-white/10 p-[1.2vw]">Sync</div><div className="rounded-[0.7vw] bg-white/10 p-[1.2vw]">Notifications</div><div className="rounded-[0.7vw] bg-white/10 p-[1.2vw]">Master Data</div><div className="rounded-[0.7vw] bg-white/10 p-[1.2vw]">Settings</div><div className="col-span-2 rounded-[0.7vw] bg-teal-500/30 p-[1.2vw]">Feedback</div></div></aside>
    </main>
    <footer className="flex items-center justify-between border-t border-slate-200 pt-[2vh] text-[1.5vw] font-medium text-slate-400"><span>QMS360 Platform</span><span>Architecture Overview • 03</span></footer>
  </div>;
}
