export default function RuntimeAndFlows() {
  return <div className="w-screen h-screen overflow-hidden relative bg-bg px-[4vw] py-[4vh] font-body text-primary grid grid-rows-[auto_auto_1fr_auto] gap-y-[2vh]">
    <header className="flex items-center justify-between border-b border-slate-200 pb-[2vh]"><div className="flex items-center gap-[1vw]"><div className="h-[2vw] w-[2vw] rounded-[0.4vw] bg-accent"></div><span className="text-[1.5vw] font-bold">QMS360</span></div><span className="text-[1.5vw] font-semibold text-muted">DELIVERY + FLOWS</span></header>
    <div><p className="text-[1.5vw] font-bold uppercase tracking-[0.12em] text-accent">Operating model</p><h1 className="text-[3.6vw] font-extrabold tracking-[-0.035em]">Runtime, delivery, and end-to-end flows</h1></div>
    <main className="grid grid-cols-[0.82fr_1.18fr] gap-[2vw]">
      <section className="rounded-[1vw] bg-primary p-[1.7vw] text-white"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-teal-300">Delivery foundation</p><div className="mt-[1.5vh] space-y-[1.1vh]"><p className="rounded-[0.7vw] bg-white/10 p-[1vw] text-[1.5vw] leading-[1.35]"><strong>Monorepo:</strong> pnpm workspaces for applications and shared TypeScript libraries</p><p className="rounded-[0.7vw] bg-white/10 p-[1vw] text-[1.5vw] leading-[1.35]"><strong>Build:</strong> Vite bundles the web app; esbuild produces the API ESM bundle with source maps</p><p className="rounded-[0.7vw] bg-white/10 p-[1vw] text-[1.5vw] leading-[1.35]"><strong>Runtime:</strong> Replit workflows expose the web application and route /api to the backend</p><p className="rounded-[0.7vw] bg-teal-500/30 p-[1vw] text-[1.5vw] leading-[1.35]"><strong>Quality gates:</strong> TypeScript checks, Vitest suites, OpenAPI code generation, and Playwright end-to-end coverage</p></div></section>
      <section className="flex flex-col justify-between gap-[1.1vh]">
        <div className="rounded-[0.9vw] border border-teal-200 bg-teal-50 p-[1.2vw]"><div className="flex items-center gap-[1vw]"><span className="flex h-[3vw] w-[3vw] items-center justify-center rounded-full bg-accent text-[1.5vw] font-extrabold text-white">1</span><div><p className="text-[1.6vw] font-extrabold">Login flow</p><p className="mt-[0.4vh] text-[1.5vw] leading-[1.35] text-muted">credentials → bcrypt verification → JWT → authenticated /auth/me context</p></div></div></div>
        <div className="rounded-[0.9vw] border border-slate-200 bg-white p-[1.2vw] shadow-[0_0.4vw_1vw_rgba(30,58,95,0.05)]"><div className="flex items-center gap-[1vw]"><span className="flex h-[3vw] w-[3vw] items-center justify-center rounded-full bg-slate-100 text-[1.5vw] font-extrabold">2</span><div><p className="text-[1.6vw] font-extrabold">CRUD flow</p><p className="mt-[0.4vh] text-[1.5vw] leading-[1.35] text-muted">React Query hook → generated fetch client → Express/RBAC/Zod → Drizzle/PostgreSQL → cache refresh</p></div></div></div>
        <div className="rounded-[0.9vw] border border-slate-200 bg-white p-[1.2vw] shadow-[0_0.4vw_1vw_rgba(30,58,95,0.05)]"><div className="flex items-center gap-[1vw]"><span className="flex h-[3vw] w-[3vw] items-center justify-center rounded-full bg-slate-100 text-[1.5vw] font-extrabold">3</span><div><p className="text-[1.6vw] font-extrabold">Evidence flow</p><p className="mt-[0.4vh] text-[1.5vw] leading-[1.35] text-muted">browser upload → authenticated API → private object storage → controlled retrieval</p></div></div></div>
        <div className="grid grid-cols-3 gap-[1vw] rounded-[0.9vw] border border-slate-200 bg-white p-[1.2vw] text-center"><div><p className="text-[1.5vw] font-bold text-accent">Web</p><p className="text-[1.5vw] text-muted">Vite</p></div><div className="border-x border-slate-200"><p className="text-[1.5vw] font-bold text-accent">API</p><p className="text-[1.5vw] text-muted">esbuild</p></div><div><p className="text-[1.5vw] font-bold text-accent">Data</p><p className="text-[1.5vw] text-muted">PostgreSQL</p></div></div>
      </section>
    </main>
    <footer className="flex items-center justify-between border-t border-slate-200 pt-[2vh] text-[1.5vw] font-medium text-slate-400"><span>QMS360 Platform</span><span>Architecture Overview • 06</span></footer>
  </div>;
}
