export default function SecurityAndServices() {
  return <div className="w-screen h-screen overflow-hidden relative bg-bg px-[4vw] py-[4vh] font-body text-primary grid grid-rows-[auto_auto_1fr_auto] gap-y-[2.2vh]">
    <header className="flex items-center justify-between border-b border-slate-200 pb-[2vh]"><div className="flex items-center gap-[1vw]"><div className="h-[2vw] w-[2vw] rounded-[0.4vw] bg-accent"></div><span className="text-[1.5vw] font-bold">QMS360</span></div><span className="text-[1.5vw] font-semibold text-muted">CROSS-CUTTING SERVICES</span></header>
    <div><p className="text-[1.5vw] font-bold uppercase tracking-[0.12em] text-accent">Trust and extension points</p><h1 className="text-[3.7vw] font-extrabold tracking-[-0.035em]">Security, files, notifications, and VerionAI</h1></div>
    <main className="grid grid-cols-[1.05fr_0.95fr] gap-[2vw]">
      <section className="grid grid-cols-2 gap-[1.2vw]">
        <div className="rounded-[0.9vw] border border-teal-200 bg-teal-50 p-[1.4vw]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-accent">Authentication</p><p className="mt-[1vh] text-[1.6vw] leading-[1.4] text-primary">bcrypt password verification and signed JWT bearer tokens</p></div>
        <div className="rounded-[0.9vw] border border-slate-200 bg-white p-[1.4vw]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-muted">Authorization</p><p className="mt-[1vh] text-[1.55vw] leading-[1.38] text-primary">organization isolation, application access, RBAC grants, ownership rules, and project scope</p></div>
        <div className="rounded-[0.9vw] border border-slate-200 bg-white p-[1.4vw]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-muted">Files</p><p className="mt-[1vh] text-[1.6vw] leading-[1.4] text-primary">private object storage with authenticated metadata and download paths</p></div>
        <div className="rounded-[0.9vw] border border-slate-200 bg-white p-[1.4vw]"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-muted">Notifications</p><p className="mt-[1vh] text-[1.6vw] leading-[1.4] text-primary">in-app records plus SMTP delivery through Nodemailer</p></div>
        <div className="col-span-2 rounded-[0.9vw] bg-primary p-[1.4vw] text-white"><p className="text-[1.5vw] font-bold uppercase tracking-wide text-teal-300">Integration safety</p><p className="mt-[1vh] text-[1.6vw] leading-[1.4]">encrypted connector secrets, DNS validation, host allowlists, IP pinning, and delivery health tracking</p></div>
      </section>
      <aside className="relative flex flex-col justify-center rounded-[1vw] border border-slate-200 bg-white p-[2vw] shadow-[0_0.8vw_2vw_rgba(30,58,95,0.08)]"><div className="absolute right-[2vw] top-[2vh] h-[7vw] w-[7vw] rounded-full border-[1.2vw] border-teal-100"></div><p className="relative text-[1.5vw] font-bold uppercase tracking-[0.12em] text-accent">VerionAI</p><h2 className="relative mt-[1vh] max-w-[32vw] text-[3vw] font-extrabold leading-[1.08] tracking-tight">Structured AI inside governed workflows</h2><p className="relative mt-[2.4vh] text-[1.65vw] leading-[1.45] text-muted">Anthropic-compatible proxy for rephrasing, quality briefs, feedback triage, and transaction extraction</p><div className="relative mt-[3vh] grid grid-cols-2 gap-[1vw] text-[1.5vw] font-semibold"><p className="rounded-[0.7vw] bg-slate-50 p-[1vw]">Bounded prompts</p><p className="rounded-[0.7vw] bg-slate-50 p-[1vw]">Structured JSON parsing</p><p className="rounded-[0.7vw] bg-slate-50 p-[1vw]">Timeouts</p><p className="rounded-[0.7vw] bg-teal-50 p-[1vw] text-accent">Audit logging</p></div></aside>
    </main>
    <footer className="flex items-center justify-between border-t border-slate-200 pt-[2vh] text-[1.5vw] font-medium text-slate-400"><span>QMS360 Platform</span><span>Architecture Overview • 05</span></footer>
  </div>;
}
