export default function SystemTopology() {
  return <div className="w-screen h-screen overflow-hidden relative bg-bg px-[4vw] py-[4vh] font-body text-primary grid grid-rows-[auto_auto_1fr_auto] gap-y-[2.5vh]">
    <header className="flex items-center justify-between border-b border-slate-200 pb-[2vh]"><div className="flex items-center gap-[1vw]"><div className="h-[2vw] w-[2vw] rounded-[0.4vw] bg-accent"></div><span className="text-[1.5vw] font-bold">QMS360</span></div><span className="text-[1.5vw] font-semibold text-muted">SYSTEM TOPOLOGY</span></header>
    <div><p className="text-[1.5vw] font-bold uppercase tracking-[0.12em] text-accent">Layered architecture</p><h1 className="text-[4vw] font-extrabold tracking-[-0.035em]">System topology: one platform, clear layers</h1></div>
    <main className="grid grid-cols-[0.85fr_1fr_1fr_1fr_0.95fr] items-center gap-[1.4vw]">
      <div className="rounded-[1vw] border border-slate-200 bg-white p-[1.5vw] text-center shadow-[0_0.5vw_1.5vw_rgba(30,58,95,0.06)]"><div className="mx-auto flex h-[5vw] w-[5vw] items-center justify-center rounded-full bg-teal-50 text-[2.5vw] font-extrabold text-accent">01</div><h2 className="mt-[2vh] text-[2vw] font-bold">Users</h2><p className="mt-[1vh] text-[1.55vw] leading-[1.4] text-muted">Users access the QMS360 React single-page application</p></div>
      <div className="relative rounded-[1vw] border border-teal-200 bg-teal-50 p-[1.5vw] text-center"><span className="absolute left-[-1.25vw] top-1/2 text-[2.6vw] text-accent">→</span><div className="mx-auto flex h-[5vw] w-[5vw] items-center justify-center rounded-full bg-accent text-[2.5vw] font-extrabold text-white">02</div><h2 className="mt-[2vh] text-[2vw] font-bold">Web layer</h2><p className="mt-[1vh] text-[1.55vw] leading-[1.4] text-muted">Wouter routes domain pages; React Query manages server state</p></div>
      <div className="relative rounded-[1vw] border border-slate-200 bg-white p-[1.5vw] text-center shadow-[0_0.5vw_1.5vw_rgba(30,58,95,0.06)]"><span className="absolute left-[-1.25vw] top-1/2 text-[2.6vw] text-accent">→</span><div className="mx-auto flex h-[5vw] w-[5vw] items-center justify-center rounded-full bg-slate-100 text-[2.5vw] font-extrabold">03</div><h2 className="mt-[2vh] text-[2vw] font-bold">API contract</h2><p className="mt-[1vh] text-[1.55vw] leading-[1.4] text-muted">Generated OpenAPI client sends authenticated requests to /api</p></div>
      <div className="relative rounded-[1vw] border border-slate-200 bg-white p-[1.5vw] text-center shadow-[0_0.5vw_1.5vw_rgba(30,58,95,0.06)]"><span className="absolute left-[-1.25vw] top-1/2 text-[2.6vw] text-accent">→</span><div className="mx-auto flex h-[5vw] w-[5vw] items-center justify-center rounded-full bg-slate-100 text-[2.5vw] font-extrabold">04</div><h2 className="mt-[2vh] text-[2vw] font-bold">Service layer</h2><p className="mt-[1vh] text-[1.55vw] leading-[1.4] text-muted">Express routes apply authentication, tenant scope, RBAC, and validation</p></div>
      <div className="relative rounded-[1vw] border border-slate-200 bg-white p-[1.5vw] text-center shadow-[0_0.5vw_1.5vw_rgba(30,58,95,0.06)]"><span className="absolute left-[-1.25vw] top-1/2 text-[2.6vw] text-accent">→</span><div className="mx-auto flex h-[5vw] w-[5vw] items-center justify-center rounded-full bg-slate-100 text-[2.5vw] font-extrabold">05</div><h2 className="mt-[2vh] text-[2vw] font-bold">Data + services</h2><p className="mt-[1vh] text-[1.5vw] leading-[1.35] text-muted">Drizzle ORM reads and writes PostgreSQL domain schemas</p><p className="mt-[1vh] text-[1.5vw] leading-[1.35] text-muted">Object storage holds files; SMTP and Anthropic proxy provide external services</p></div>
    </main>
    <footer className="flex items-center justify-between border-t border-slate-200 pt-[2vh] text-[1.5vw] font-medium text-slate-400"><span>QMS360 Platform</span><span>Architecture Overview • 02</span></footer>
  </div>;
}
